name = "BcdiCli"
uuid = "a71e6163-0ec9-4b89-aa25-9ba4ebda5fa6"
authors = ["Jason Meziere"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
